swagger: "2.0"
info:
  title: Users store
  description: Service for store users.
  version: 1.0.0
host: localhost:50877
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    get:
      tags:
        - users
      responses:
        200:
          description: list users
          schema:
            type: array
            items:
              $ref: "#/definitions/user"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - users
      operationId: addOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/user"
      responses:
        201:
          description: Created user
          schema:
            $ref: "#/definitions/user"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /users/{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    get:
      tags:
        - users
      operationId: getOne
      responses:
        200:
          description: get user by id
          schema:
              $ref: "#/definitions/user"
        404:
          description: User not found
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    put:
      tags:
        - users
      operationId: updateOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/user"
      responses:
        200:
          description: Update user
          schema:
            $ref: "#/definitions/user"
        404:
          description: User not found
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - users
      operationId: deleteOne
      responses:
        204:
          description: Deleted user
        404:
          description: User not found
        default:
          description: error
          schema:
            $ref: "#/definitions/error"

definitions:
  user:
    properties:
      id:
        type: integer
        description: The user ID.
        format: int64
        readOnly: true
      name:
        type: string
        description: The user name
        minLength: 3
      birth_date:
        type: string
        description: The user birth date
        pattern: '[0-9]{2}-[0-9]{2}-[0-9]{4}'
        example: "12-05-1980"
    required:
      - name
      - birth_date
  error:
    type: object
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string