// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Users store
//
//  Service for store users.
//  Schemes:
//    http
//  Host: localhost:50877
//  BasePath: /api/v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
