// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"user-store/internal/models"
)

// DeleteOneNoContentCode is the HTTP code returned for type DeleteOneNoContent
const DeleteOneNoContentCode int = 204

/*DeleteOneNoContent Deleted user

swagger:response deleteOneNoContent
*/
type DeleteOneNoContent struct {
}

// NewDeleteOneNoContent creates DeleteOneNoContent with default headers values
func NewDeleteOneNoContent() *DeleteOneNoContent {

	return &DeleteOneNoContent{}
}

// WriteResponse to the client
func (o *DeleteOneNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteOneNotFoundCode is the HTTP code returned for type DeleteOneNotFound
const DeleteOneNotFoundCode int = 404

/*DeleteOneNotFound User not found

swagger:response deleteOneNotFound
*/
type DeleteOneNotFound struct {
}

// NewDeleteOneNotFound creates DeleteOneNotFound with default headers values
func NewDeleteOneNotFound() *DeleteOneNotFound {

	return &DeleteOneNotFound{}
}

// WriteResponse to the client
func (o *DeleteOneNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*DeleteOneDefault error

swagger:response deleteOneDefault
*/
type DeleteOneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteOneDefault creates DeleteOneDefault with default headers values
func NewDeleteOneDefault(code int) *DeleteOneDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteOneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete one default response
func (o *DeleteOneDefault) WithStatusCode(code int) *DeleteOneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete one default response
func (o *DeleteOneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete one default response
func (o *DeleteOneDefault) WithPayload(payload *models.Error) *DeleteOneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete one default response
func (o *DeleteOneDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteOneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
